swagger: '2.0'
info:
  title: Ows-timed-release API specifications
  version: 0.0.1
host: qa-ows-timed-release.theorchard.io
basePath: /
schemes:
  - https
tags:
  - name: Health Check
    description: Check the health of the application.
  - name: Timed Release CRUD Operation
    description: Following are Timed Release Schedule CRUD Operation.
paths:
  /hello:
    get:
      tags:
        - Health Check
      description: Health check
      summary: Check the health of the application.
      responses:
        '200':
          description: 200 OK
          schema:
            type: object
            example:
              {
                "status": "ok"
              }
  /product/{product_id}:
    get:
      parameters:
        - in: path
          name: product_id
          required: true
          type: integer
      responses:
        '200':
          description: 200 OK
          schema:
            type: object
            properties:
              product:
                type: array
                items:
                  type: object
                  properties:
                    product_id:
                      type: integer
                    time_of_day_product:
                      type: string
                    time_zone:
                      type: string
                    store_id:
                      type: integer
                  required:
                    - product_id
                    - time_of_day_product
                    - time_zone
            required:
              - product
            example:
              {
                "product": {
                  "product_id": 2080168,
                  "time_of_day_product": "20:15:00",
                  "time_zone": "local",
                  "store_id": 286
                }
              }
        '404':
          description: 404 Product not found
          schema:
            properties:
              code:
                type: string
              message:
                type: string
            required:
              - message
              - code
            type: object
            example:
              {
                "message": "Requested product id <product_id> not found.",
                "code": "not_found_error"
              }
        '400':
          description: 400 Bad request
          schema:
            properties:
              code:
                type: string
              message:
                type: string
            required:
              - message
              - code
            type: object
            example:
              {
                "message": "<product_id> must be integer and greater than zero",
                "code": "bad_request"
              }
        '500':
          description: 500 Internal server error
          schema:
            properties:
              code:
                type: string
              message:
                type: string
            required:
              - message
              - code
            type: object
            example:
              {
                "message": "Could not connect to MySQL",
                "code": "server_error"
              }
      description: Get product live time detail for given product id.
      summary: Returns product live time detail.
      tags:
        - Timed Release CRUD Operation
  /product:
    post:
      parameters:
        - in: header
          name: Correlation-Id
          required: false
          type: string
        - in: body
          name: body
          schema:
            example:
              {
                "product_id": 2080168,
                "time_of_day_product": "20:15:00",
                "time_zone": "local",
                "store_id": 287
              }
      responses:
        '200':
          description: 200 OK
          schema:
            type: object
            properties:
              product:
                type: array
                items:
                  type: object
                  properties:
                    product_id:
                      type: integer
                    time_of_day_product:
                      type: string
                    time_zone:
                      type: string
                    store_id:
                      type: integer
                  required:
                    - product_id
                    - time_of_day_product
                    - time_zone
            required:
              - product
            example:
              {
                "product": {
                  "product_id": 2080168,
                  "time_of_day_product": "20:15:00",
                  "time_zone": "local",
                  "store_id": 286
                }
              }
        '400':
          description: 400 Bad request
          schema:
            properties:
              code:
                type: string
              message:
                type: string
            required:
              - message
              - code
            type: object
            example:
              {
                "message": [
                  {
                    "non integer or negative fields list": [
                      "product_id",
                      "store_id"
                    ]
                  },
                  {
                    "invalid time zone": "Time of day Product should be in valid HH:MM:SS format"
                  },
                  {
                    "invalid time format": "Time Zone should be GMT or local"
                  }
                ],
                "code": "bad_request"
              }
        '500':
          description: 500 Internal server error
          schema:
            properties:
              code:
                type: string
              message:
                type: string
            required:
              - message
              - code
            type: object
            example:
              {
                "message": "Could not connect to MySQL",
                "code": "server_error"
              }
      description: Save info about product live time detail.
      summary: Create product live time detail.
      tags:
        - Timed Release CRUD Operation
definitions: {}
securityDefinitions: {}
